#!/bin/bash
while getopts :qwe opt
do
	case $opt in
		q)
			agents=()
			echo -n "Add meg az agent nevét: "
			read AGENT
			echo -n "add meg hány abilitye van: "
			read abilities
			echo -n "Az agent neme: (0)nő/(1)férfi"
			read NEM
			agents=("$AGENT" "$abilities" "$NEM")
			filename='agents.txt'
        		if [ -f "$filename" ];
        		then
                		printf "%s:%s:%s\n" "${agents[@]}" >>agents.txt
        		else
                		echo "Név:Abilities:Nem" >>agents.txt
                		printf "%s:%s:%s\n" "${agents[@]}" >>agents.txt
        		fi
			;;
		w)
			echo -n "Milyen nemre szeretnél szűrni?"
			read milyen_nem
			while IFS=':' read -r agent abilities nem
			do

				if [ "$milyen_nem" == "férfi" ];
				then

					grep -c "1"
				else
					grep -c "0"
				fi
			done < agents.txt
			;;
		e)
			echo "Az öszes agent listájának letöltése :"
			curl -L "https://drive.google.com/uc?export=download&id=1rmqM5-SI_99-PjVSdnXXnHmLWcvAiere" -o agent_nevek.zip
			;;
		?)
			echo "nem ismert opció: $OPTARG"
			;;

	esac

done
